"""데모 샘플 데이터 (기준일 2026-06-05 가정). 실제 데이터 아님 — 미리보기용."""
from core import schema

SEED = {
    schema.SHEET_SCHEDULE: [
        {"content_id": "C-001", "title": "일본여행보험 정보형 원고", "channel": "공식블로그",
         "draft_request_date": "2026-05-28", "draft_submit_date": "2026-06-03",
         "review_submit_date": "2026-06-06", "review_done_date": "",
         "publish_plan_date": "2026-06-06", "publish_actual_date": "", "status": ""},
        {"content_id": "C-002", "title": "해외여행보험 비교형 #3", "channel": "배포형",
         "draft_request_date": "2026-05-30", "draft_submit_date": "2026-06-02",
         "review_submit_date": "2026-06-04", "review_done_date": "",
         "publish_plan_date": "2026-06-08", "publish_actual_date": "", "status": ""},
        {"content_id": "C-003", "title": "항공기지연보험 후기형", "channel": "배포형",
         "draft_request_date": "2026-05-25", "draft_submit_date": "2026-05-30",
         "review_submit_date": "2026-06-01", "review_done_date": "2026-06-03",
         "publish_plan_date": "2026-06-03", "publish_actual_date": "", "status": ""},
        {"content_id": "C-004", "title": "여행자보험 가이드 원고", "channel": "공식블로그",
         "draft_request_date": "2026-05-20", "draft_submit_date": "2026-05-28",
         "review_submit_date": "2026-05-30", "review_done_date": "2026-06-02",
         "publish_plan_date": "2026-06-10", "publish_actual_date": "", "status": ""},
        {"content_id": "C-005", "title": "유럽여행보험 정보형", "channel": "배포형",
         "draft_request_date": "2026-06-01", "draft_submit_date": "",
         "review_submit_date": "", "review_done_date": "",
         "publish_plan_date": "2026-06-20", "publish_actual_date": "", "status": ""},
        {"content_id": "C-006", "title": "5월 결산 후기", "channel": "배포형",
         "draft_request_date": "2026-05-01", "draft_submit_date": "2026-05-10",
         "review_submit_date": "2026-05-12", "review_done_date": "2026-05-15",
         "publish_plan_date": "2026-05-20", "publish_actual_date": "2026-05-20", "status": ""},
    ],
    schema.SHEET_INFLUENCERS: [
        {"blogger_name": "여행마스터김", "url": "https://blog.naver.com/traveler_kim", "visitors": "12000",
         "category": "여행", "score": "88", "selected": "Y", "draft_submitted": "Y",
         "review_done": "Y", "published": "Y", "publish_url": "https://blog.naver.com/traveler_kim/223001"},
        {"blogger_name": "보험덕후이", "url": "https://blog.naver.com/insure_lee", "visitors": "8500",
         "category": "보험/재테크", "score": "76", "selected": "Y", "draft_submitted": "Y",
         "review_done": "N", "published": "N", "publish_url": ""},
        {"blogger_name": "일상기록박", "url": "https://blog.naver.com/daily_park", "visitors": "5400",
         "category": "일상", "score": "61", "selected": "Y", "draft_submitted": "N",
         "review_done": "N", "published": "N", "publish_url": ""},
        {"blogger_name": "맛집탐험최", "url": "https://blog.naver.com/food_choi", "visitors": "22000",
         "category": "맛집", "score": "92", "selected": "N", "draft_submitted": "N",
         "review_done": "N", "published": "N", "publish_url": ""},
    ],
    schema.SHEET_REVIEWS: [
        {"content_id": "C-001", "title": "일본여행보험 정보형", "review_submit_date": "2026-06-06",
         "status": "심의접수", "revision_count": "0", "review_done_date": ""},
        {"content_id": "C-002", "title": "해외여행보험 비교형 #3", "review_submit_date": "2026-06-04",
         "status": "수정요청", "revision_count": "1", "review_done_date": ""},
        {"content_id": "C-003", "title": "항공기지연보험 후기형", "review_submit_date": "2026-06-01",
         "status": "심의완료", "revision_count": "2", "review_done_date": "2026-06-03"},
        {"content_id": "C-004", "title": "여행자보험 가이드", "review_submit_date": "2026-05-30",
         "status": "심의완료", "revision_count": "1", "review_done_date": "2026-06-02"},
        {"content_id": "C-006", "title": "5월 결산 후기", "review_submit_date": "2026-05-12",
         "status": "발행완료", "revision_count": "1", "review_done_date": "2026-05-15"},
    ],
    schema.SHEET_BRIEFING: [
        {"date": "2026-06-01", "keyword": "해외여행보험", "ai_briefing_exposed": "Y",
         "samsung_exposed": "Y", "content_type": "정보형"},
        {"date": "2026-06-03", "keyword": "여행자보험", "ai_briefing_exposed": "Y",
         "samsung_exposed": "N", "content_type": "비교형"},
        {"date": "2026-06-05", "keyword": "일본여행보험", "ai_briefing_exposed": "N",
         "samsung_exposed": "N", "content_type": "후기형"},
        {"date": "2026-06-07", "keyword": "항공기지연보험", "ai_briefing_exposed": "Y",
         "samsung_exposed": "Y", "content_type": "후기형"},
    ],
    schema.SHEET_REF_BANNED: [
        {"term": t, "note": "demo"} for t in
        ["무조건", "전부 보장", "훨씬", "걱정 없이", "모두", "빈번하게", "자주", "는 물론", "뿐만 아니라", "100%", "완벽", "최고"]
    ],
    schema.SHEET_REF_REQUIRED: [
        {"phrase": "유료광고", "type": "유료광고", "note": "demo"},
        {"phrase": "본 광고는 상품 가입을 권유하는 목적", "type": "고지", "note": "demo"},
    ],
    schema.SHEET_REF_RIDERS: [
        {"official_name": "항공기 지연 결항 보상(지수형)(국내 출국) 특약",
         "common_mistakes": "항공기 지연 특약,항공기지연특약,지연보상 특약"},
        {"official_name": "해외여행 실손의료비(상해) 특약",
         "common_mistakes": "해외 실손 특약,실손 특약"},
    ],
    schema.SHEET_REF_KEYWORDS: [
        {"keyword": "해외여행보험", "type": "키워드"},
        {"keyword": "여행자보험", "type": "키워드"},
        {"keyword": "해외여행자보험", "type": "키워드"},
        {"keyword": "해외여행보험", "type": "해시태그"},
    ],
    schema.SHEET_CALENDAR: [
        {"date": "2026-06-01", "task": "배포형 모집 (7월)", "track": "배포형"},
        {"date": "2026-06-05", "task": "공식 업로드 (6월) - 1건", "track": "공식"},
        {"date": "2026-06-08", "task": "바이럴 방향성 확정 (7월)", "track": ""},
        {"date": "2026-06-08", "task": "배포형 작성 (7월)", "track": "배포형"},
        {"date": "2026-06-08", "task": "공식 작성 (7월)", "track": "공식"},
        {"date": "2026-06-11", "task": "배포형 배포 (6월) - 2건", "track": "배포형"},
        {"date": "2026-06-12", "task": "배포형 심의, 수정 (7월)", "track": "배포형"},
        {"date": "2026-06-12", "task": "공식 심의, 수정 (7월)", "track": "공식"},
        {"date": "2026-06-15", "task": "배포형 심의, 수정 (7월)", "track": "배포형"},
        {"date": "2026-06-15", "task": "공식 심의, 수정 (7월)", "track": "공식"},
        {"date": "2026-06-17", "task": "배포형 배포 (6월) - 2건", "track": "배포형"},
        {"date": "2026-06-22", "task": "배포형 배포 (6월) - 2건", "track": "배포형"},
        {"date": "2026-06-22", "task": "배포형 심의, 수정 (7월)", "track": "배포형"},
        {"date": "2026-06-22", "task": "공식 심의, 수정 (7월)", "track": "공식"},
        {"date": "2026-06-24", "task": "공식 업로드 (6월) - 1건", "track": "공식"},
        {"date": "2026-06-24", "task": "배포형 심의 완료 (7월)", "track": "배포형"},
        {"date": "2026-06-24", "task": "공식 심의 완료 (7월)", "track": "공식"},
        {"date": "2026-06-25", "task": "배포형 배포 (6월) - 2건", "track": "배포형"},
        {"date": "2026-06-30", "task": "배포형 배포 (6월) - 2건", "track": "배포형"},
    ],
    schema.SHEET_DISTRIBUTION: [
        # 배포형 (5월 작성) — 블로거 10명
        {"group": "배포형 (5월 작성)", "blogger": "떠네르", "publish_date": "", "approval_no": "준법감시인확인필 제26-1-3643호 (4078,'26.05.22~'27.05.21)", "landing_url": "", "note": "", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "린덴", "publish_date": "", "approval_no": "준법감시인확인필 제26-1-3644호 (4078,'26.05.22~'27.05.21)", "landing_url": "", "note": "", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "봉봉츄", "publish_date": "", "approval_no": "준법감시인확인필 제26-1-3690호 (4078,'26.05.27~'27.05.26)", "landing_url": "", "note": "", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "새콤한 복숭아", "publish_date": "", "approval_no": "준법감시인확인필 제26-1-3691호 (4078,'26.05.27~'27.05.26)", "landing_url": "", "note": "", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "쏭쏭", "publish_date": "", "approval_no": "준법감시인확인필 제26-1-3706호 (4078,'26.05.27~'27.05.26)", "landing_url": "", "note": "", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "에버", "publish_date": "", "approval_no": "준법감시인확인필 제26-1-3707호 (4078,'26.05.27~'27.05.26)", "landing_url": "", "note": "", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "유체이", "publish_date": "", "approval_no": "", "landing_url": "", "note": "심의 진행중", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "쟁토리", "publish_date": "", "approval_no": "", "landing_url": "", "note": "심의 진행중", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "짠순록", "publish_date": "", "approval_no": "준법감시인확인필 제26-1-3758호 (4078,'26.05.28~'27.05.27)", "landing_url": "", "note": "", "publish_url": ""},
        {"group": "배포형 (5월 작성)", "blogger": "헬로우귀티", "publish_date": "", "approval_no": "준법감시인확인필 제26-1-3759호 (4078,'26.05.28~'27.05.27)", "landing_url": "", "note": "", "publish_url": ""},
        # 공식블로그
        {"group": "공식블로그", "blogger": "쿨케이션", "publish_date": "2026-06-05", "approval_no": "준법감시인확인필 제26-1-3654호 (4078,'26.05.22~'27.05.21)", "landing_url": "https://direct.samsungfire.com/vd/overture_index.jsp?OTK=F2606VR0002", "note": "6/8 URL 갈음 필요", "publish_url": ""},
        {"group": "공식블로그", "blogger": "여름장마", "publish_date": "2026-06-24", "approval_no": "준법감시인확인필 제26-1-3755호 (4078,'26.05.28~'27.05.27)", "landing_url": "https://direct.samsungfire.com/vd/overture_index.jsp?OTK=F2606VR0003", "note": "", "publish_url": ""},
        # 변경심의 진행 건 (청년도약할인 내용 삭제)
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "차니차니", "publish_date": "2026-06-01", "approval_no": "준법감시인확인필 제26-1-3855호 (4078,'26.06.01~'27.05.31)", "landing_url": "", "note": "변경심의 완료", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "민나", "publish_date": "2026-06-01", "approval_no": "준법감시인확인필 제26-1-3854호 (4078,'26.06.01~'27.05.31)", "landing_url": "", "note": "변경심의 완료", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "릴라킹", "publish_date": "", "approval_no": "", "landing_url": "", "note": "변경심의 진행중", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "기동이", "publish_date": "", "approval_no": "", "landing_url": "", "note": "변경심의 진행중", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "요치요치", "publish_date": "2026-05-28", "approval_no": "준법감시인확인필 제26-1-3761호 (4078,'26.05.28~'27.05.27)", "landing_url": "", "note": "변경심의 완료", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "린린", "publish_date": "2026-05-28", "approval_no": "준법감시인확인필 제26-1-3760호 (4078,'26.05.28~'27.05.27)", "landing_url": "", "note": "변경심의 완료", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "나혜", "publish_date": "2026-06-01", "approval_no": "준법감시인확인필 제26-1-3850호 (4078,'26.06.01~'27.05.31)", "landing_url": "", "note": "변경심의 완료", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "기린아", "publish_date": "2026-06-01", "approval_no": "준법감시인확인필 제26-1-3851호 (4078,'26.06.01~'27.05.31)", "landing_url": "", "note": "변경심의 완료", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "쿙이", "publish_date": "2026-06-01", "approval_no": "준법감시인확인필 제26-1-3857호 (4078,'26.06.01~'27.05.31)", "landing_url": "", "note": "변경심의 완료", "publish_url": ""},
        {"group": "변경심의 (청년도약할인 삭제)", "blogger": "카라", "publish_date": "2026-06-01", "approval_no": "준법감시인확인필 제26-1-3856호 (4078,'26.06.01~'27.05.31)", "landing_url": "", "note": "변경심의 완료", "publish_url": ""},
    ],
}
